import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
export default function Home({ posts: { data } }: any) {
  console.log(data);

  const posts = data.map((post: any) => {
    return (
      <div key={post.id}>
        <div>
          <h2>{post.attributes.title}</h2>
        </div>
      </div>
    );
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts}
    </div>
  );
}

export const getStaticProps = async () => {
  const postsResponse = await axios.get("http://localhost:1337/api/posts");

  return {
    props: {
      posts: postsResponse.data,
    },
    revalidate: 10,
  };
};
