import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { POSTS_API } from "../constants/paths";
import { Header } from "../components/Header/Header";
import { Posts } from "../components/Posts/Posts";
import { postsI } from "../constants/types";

export default function Home({ data: { data } }: postsI) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Posts data={data} />
    </div>
  );
}

export const getStaticProps = async () => {
  const postsResponse = await axios.get(POSTS_API);

  return {
    props: {
      data: postsResponse.data,
    },
    revalidate: 10,
  };
};
